"""Single source of truth for Bavly Kamel's published and planned projects."""

PROJECTS = [
    {
        "slug": "10-day-goal-tracker",
        "number": "01",
        "featured": True,
        "name": "10-Day Goal Tracker",
        "category": "Flask · Productivity",
        "status": "Existing project",
        "status_kind": "available",
        "summary": "A personal goal-tracking web app for creating custom 10-day cycles, managing goals, tracking progress and streaks, reflecting on outcomes, and exporting cycles as PDFs.",
        "technologies": ["Python", "Flask", "Jinja2", "WeasyPrint", "JSON", "CSS"],
        "features": [
            "Create custom cycles with start and end dates",
            "Add, edit, delete, and reorder goals",
            "Track progress percentages and streaks",
            "Archive completed cycles",
            "Reflect on what went well, what did not, and what was learned",
            "Export cycles as PDFs",
            "Show confirmation prompts before deleting important data",
        ],
        "sections": [
            ("Inspiration", "I used to track goals on paper, but rewriting them, calculating progress by hand, and staying consistent without much feedback became repetitive. This app turns that personal system into a working web application."),
            ("Building the app", "Starting from an empty project, I added the features one by one and learned Flask from the ground up. I built it to understand how each part works instead of relying on a ready-made template."),
            ("Reflection", "The project let me turn a simple paper routine into a tool I can use, while learning through the process of building and improving it feature by feature."),
        ],
        "github": "https://github.com/BavlyK100/tracker_app",
        "linkedin": "https://lnkd.in/p/eVyAKW4x",
        "demo": None,
        "featured_visual": {
            "label": "FROM PAPER TO APP",
            "before": ["Rewrite goals", "Manual progress", "Little feedback", "Paper notes"],
            "after": ["Custom cycles", "Progress & streaks", "Reflections", "PDF export"],
            "footnote": "A personal system, built into an app",
        },
    },
    {
        "slug": "egyptian-housing-market-analysis",
        "number": "02",
        "featured": False,
        "upcoming": True,
        "name": "Egyptian Housing Market Analysis",
        "category": "Data Analysis · Exploratory Analysis",
        "status": "Coming Soon",
        "status_kind": "planned",
        "summary": "A planned analysis of Egyptian housing data, focused on cleaning listings, exploring price patterns, and presenting useful visual insights.",
        "technologies": ["Python", "Pandas", "NumPy", "Matplotlib", "Jupyter"],
        "features": ["Planned data cleaning and exploration", "Price visualizations", "Pattern and correlation analysis"],
        "sections": [
            ("Project status", "This project is planned and has not been built yet."),
            ("Planned focus", "Explore an Egyptian housing dataset, clean and summarize its fields, and use visualizations to investigate price patterns and relationships."),
        ],
        "github": None,
        "demo": None,
    },
    {
        "slug": "customer-churn-prediction",
        "number": "03",
        "featured": False,
        "upcoming": True,
        "name": "Customer Churn Prediction",
        "category": "Machine Learning · Classification",
        "status": "Coming Soon",
        "status_kind": "planned",
        "summary": "A planned classification project exploring how customer and service data can be prepared and used to predict churn.",
        "technologies": ["Python", "Pandas", "Scikit-learn", "Matplotlib"],
        "features": ["Planned data preprocessing", "Feature selection", "Model training and evaluation"],
        "sections": [
            ("Project status", "This project is planned and has not been built yet."),
            ("Planned focus", "Prepare customer data, explore useful features, and train and evaluate a classification model. Metrics and conclusions will be added after the project is completed."),
        ],
        "github": None,
        "demo": None,
    },
    {
        "slug": "loan-approval-predictor",
        "number": "04",
        "featured": False,
        "upcoming": True,
        "name": "Loan Approval Predictor",
        "category": "Flask · Machine Learning",
        "status": "Coming Soon",
        "status_kind": "planned",
        "summary": "A planned web application connecting a Flask API to a machine learning model for a sample loan approval prediction flow.",
        "technologies": ["Python", "Flask", "Scikit-learn", "HTML", "CSS", "JavaScript", "REST API"],
        "features": ["Planned loan input form", "Flask prediction endpoint", "Model-backed response"],
        "sections": [
            ("Project status", "This project is planned and has not been built yet."),
            ("Planned focus", "Build a small web flow that validates sample inputs, passes them to a Flask endpoint, and returns a prediction from a trained model. Model evaluation and limitations will be documented when available."),
        ],
        "github": None,
        "demo": None,
    },
    {
        "slug": "ecommerce-analytics-dashboard",
        "number": "05",
        "featured": False,
        "upcoming": True,
        "name": "E-commerce Analytics Dashboard",
        "category": "SQL · Database Analytics",
        "status": "Coming Soon",
        "status_kind": "planned",
        "summary": "A planned SQL and analytics project using an e-commerce database to explore orders, products, customers, and payments.",
        "technologies": ["SQL", "Database", "Python", "Data Analysis"],
        "features": ["Planned relational data model", "SQL joins and aggregations", "Order and product trend analysis"],
        "sections": [
            ("Project status", "This project is planned and has not been built yet."),
            ("Planned focus", "Design a small relational dataset and use SQL queries to explore revenue, products, customer behavior, order trends, and payment patterns. No results are available yet."),
        ],
        "github": None,
        "demo": None,
    },
]


def get_project(slug):
    return next((project for project in PROJECTS if project["slug"] == slug), None)
