"""Single source of truth for Bavly Kamel's published and planned projects."""

PROJECTS = [
    {
        "slug": "file-organizer",
        "number": "01",
        "featured": True,
        "name": "File Organizer",
        "category": "Python · Automation",
        "status": "Existing project",
        "status_kind": "available",
        "summary": "A Python utility that sorts files into folders based on their extensions, making a cluttered directory easier to manage.",
        "technologies": ["Python", "OS", "Automation"],
        "features": ["Groups files by extension", "Automates repetitive file management"],
        "sections": [
            ("Problem", "Sorting files by hand is repetitive and makes busy folders difficult to navigate."),
            ("Approach", "Use Python's operating-system tools to inspect file extensions and move files into matching folders."),
            ("Implementation", "The project uses Python to organize files into folders based on their extensions."),
            ("What I learned", "[Add a short note about what you learned while building this project.]"),
        ],
        "github": "https://github.com/BavlyK100/tracker_app",
        "linkedin": "https://lnkd.in/p/eVyAKW4x",
        "demo": None,
    },
    {
        "slug": "egyptian-housing-market-analysis",
        "number": "02",
        "featured": False,
        "upcoming": True,
        "name": "Egyptian Housing Market Analysis",
        "category": "Data Analysis · Exploratory Analysis",
        "status": "Coming Soon",
        "status_kind": "planned",
        "summary": "A planned analysis of Egyptian housing data, focused on cleaning listings, exploring price patterns, and presenting useful visual insights.",
        "technologies": ["Python", "Pandas", "NumPy", "Matplotlib", "Jupyter"],
        "features": ["Planned data cleaning and exploration", "Price visualizations", "Pattern and correlation analysis"],
        "sections": [
            ("Project status", "This project is planned and has not been built yet."),
            ("Planned focus", "Explore an Egyptian housing dataset, clean and summarize its fields, and use visualizations to investigate price patterns and relationships."),
        ],
        "github": None,
        "demo": None,
    },
    {
        "slug": "customer-churn-prediction",
        "number": "03",
        "featured": False,
        "upcoming": True,
        "name": "Customer Churn Prediction",
        "category": "Machine Learning · Classification",
        "status": "Coming Soon",
        "status_kind": "planned",
        "summary": "A planned classification project exploring how customer and service data can be prepared and used to predict churn.",
        "technologies": ["Python", "Pandas", "Scikit-learn", "Matplotlib"],
        "features": ["Planned data preprocessing", "Feature selection", "Model training and evaluation"],
        "sections": [
            ("Project status", "This project is planned and has not been built yet."),
            ("Planned focus", "Prepare customer data, explore useful features, and train and evaluate a classification model. Metrics and conclusions will be added after the project is completed."),
        ],
        "github": None,
        "demo": None,
    },
    {
        "slug": "loan-approval-predictor",
        "number": "04",
        "featured": False,
        "upcoming": True,
        "name": "Loan Approval Predictor",
        "category": "Flask · Machine Learning",
        "status": "Coming Soon",
        "status_kind": "planned",
        "summary": "A planned web application connecting a Flask API to a machine learning model for a sample loan approval prediction flow.",
        "technologies": ["Python", "Flask", "Scikit-learn", "HTML", "CSS", "JavaScript", "REST API"],
        "features": ["Planned loan input form", "Flask prediction endpoint", "Model-backed response"],
        "sections": [
            ("Project status", "This project is planned and has not been built yet."),
            ("Planned focus", "Build a small web flow that validates sample inputs, passes them to a Flask endpoint, and returns a prediction from a trained model. Model evaluation and limitations will be documented when available."),
        ],
        "github": None,
        "demo": None,
    },
    {
        "slug": "ecommerce-analytics-dashboard",
        "number": "05",
        "featured": False,
        "upcoming": True,
        "name": "E-commerce Analytics Dashboard",
        "category": "SQL · Database Analytics",
        "status": "Coming Soon",
        "status_kind": "planned",
        "summary": "A planned SQL and analytics project using an e-commerce database to explore orders, products, customers, and payments.",
        "technologies": ["SQL", "Database", "Python", "Data Analysis"],
        "features": ["Planned relational data model", "SQL joins and aggregations", "Order and product trend analysis"],
        "sections": [
            ("Project status", "This project is planned and has not been built yet."),
            ("Planned focus", "Design a small relational dataset and use SQL queries to explore revenue, products, customer behavior, order trends, and payment patterns. No results are available yet."),
        ],
        "github": None,
        "demo": None,
    },
]


def get_project(slug):
    return next((project for project in PROJECTS if project["slug"] == slug), None)
